# Generated by Django 4.2.4 on 2023-09-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
    ]
