# Generated by Django 4.2.4 on 2023-09-14 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_acao_options'),
        ('pesquisa', '0003_alter_resposta_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('periodo_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Período início')),
                ('periodo_fim', models.DateTimeField(blank=True, null=True, verbose_name='Período fim')),
                ('media', models.DecimalField(decimal_places=2, default=0, help_text='Média ponderada com os pesos do método CES de avaliação.', max_digits=20, verbose_name='Média')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pesquisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pesquisa.pesquisa')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sistema')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
    ]
