# Generated by Django 4.2.4 on 2023-09-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_remove_relatorio_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='respostas',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Relatório de respostas'),
        ),
    ]
