# Generated by Django 4.2.4 on 2023-09-14 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorio', '0003_relatorio_respostas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='gerado_por',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
