# Generated by Django 4.2.4 on 2023-09-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0004_remove_relatorio_gerado_por_relatorio_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='qnt_pulos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de pulos'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='qnt_respostas',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de respostas'),
        ),
    ]
