# Generated by Django 4.2.4 on 2023-08-31 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('periodo_inicio', models.DateTimeField(blank=True, help_text='A pesquisa só estará ativa a partir dessa data.', null=True, verbose_name='Período início')),
                ('periodo_fim', models.DateTimeField(blank=True, help_text='A pesquisa só estará ativa até essa data', null=True, verbose_name='Período fim')),
                ('limite_apos_pular', models.PositiveIntegerField(default=0, help_text='Quantidade de vezes que a pesquisa continuará sendo retornada, mesmo que o usuário pule.', verbose_name='Limite após pular')),
                ('afirmacao', models.TextField(default='Consegui o resultado esperado com a ação que acabei de realizar?', verbose_name='Afirmação')),
                ('acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas', to='core.acao')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
            },
        ),
    ]
