# Generated by Django 4.2.4 on 2023-09-12 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('anonima', models.BooleanField(default=False, help_text='Marque esta opção se deseja que as respostas sejam anônimas e não tenham relação direta com o participante.', verbose_name='Respostas Anônimas')),
                ('periodo_inicio', models.DateTimeField(blank=True, help_text='A pesquisa só estará ativa a partir dessa data.', null=True, verbose_name='Período início')),
                ('periodo_fim', models.DateTimeField(blank=True, help_text='A pesquisa só estará ativa até essa data', null=True, verbose_name='Período fim')),
                ('limite_pular', models.PositiveIntegerField(default=0, help_text='Quantidade máxima de vezes que um usuário pode pular a pesquisa antes de não ser mais apresentada.', verbose_name='Limite de Pulos na Pesquisa')),
                ('afirmacao', models.TextField(default='Consegui o resultado esperado com a ação que acabei de realizar?', help_text='A afirmação que a pesquisa apresenta aos participantes para avaliação.', verbose_name='Afirmação da Pesquisa')),
                ('validade_token', models.IntegerField(default=10, help_text='O período de tempo, em minutos, durante o qual o token de pesquisa permanece válido. Se o usuário não responder dentro desse período, a pesquisa ficará indisponível até que seja gerado um novo token.', verbose_name='Tempo de Validade do Token (em minutos)')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nota', models.PositiveIntegerField(default=0, verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.TextField(blank=True, null=True, verbose_name='Token')),
                ('pulos', models.PositiveIntegerField(default=0, help_text='Quantidade de vezes em que o usuário pulou a pesquisa.', verbose_name='Pulos')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='pesquisa.pesquisa')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
