# Generated by Django 4.2.4 on 2023-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_alter_resposta_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='nota',
            field=models.PositiveIntegerField(verbose_name='Nota'),
        ),
    ]
